version: "3.7"

services:
  nginx:
    image: 'nginx:1.17'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/etc/nginx/mime.types:/etc/nginx/mime.types
      - ./docker/etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: .
      args:
        PROJECT_DIR: /var/www
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - ./docker/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - redis

  redis:
    image: 'redis:6.0'
    hostname: redis

